version: '3.5'

services:
  # template-web_build:
  #   build: ../
  #   container_name: 'template-web_build'
  #   volumes:
  #     - dist:/usr/src/app/dist

  template-web_web:
    image: nginx
    ports:
      - 80:80
    container_name: 'template-web_web'
    restart: unless-stopped
    volumes:
      - ../dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
